<?php

namespace app\constants;

final class ApiErrorCode
{
  // 400
  public const VALIDATION_ERROR = 'VALIDATION_ERROR';
  public const MISSING_PARAMETER = 'MISSING_PARAMETER';
  public const INVALID_PARAMETER = 'INVALID_PARAMETER';
  public const INVALID_FORMAT = 'INVALID_FORMAT';

  // 401
  public const UNAUTHORIZED = 'UNAUTHORIZED';
  public const TOKEN_MISSING = 'TOKEN_MISSING';
  public const TOKEN_INVALID = 'TOKEN_INVALID';
  public const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
  public const REFRESH_EXPIRED = 'REFRESH_EXPIRED';

  // 403
  public const ACCESS_DENIED = 'ACCESS_DENIED';

  // 404
  public const NOT_FOUND = 'NOT_FOUND';
  public const POST_NOT_FOUND = 'POST_NOT_FOUND';
  public const COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND';
  public const NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND';
  public const SESSION_NOT_FOUND = 'SESSION_NOT_FOUND';
  public const USER_NOT_FOUND = 'USER_NOT_FOUND';
  public const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';

  // 409
  public const CONFLICT = 'CONFLICT';
  public const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
  public const USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS';
  public const SESSION_COMPROMISED = 'SESSION_COMPROMISED';

  // 422
  public const COMMENT_CONTENT_EMPTY = 'COMMENT_CONTENT_EMPTY';
  public const POST_CONTENT_EMPTY = 'POST_CONTENT_EMPTY';

  public const PROFILE_DISPLAY_NAME_EMPTY = 'PROFILE_DISPLAY_NAME_EMPTY';
  public const PROFILE_BIO_EMPTY = 'PROFILE_BIO_EMPTY';
  public const PROFILE_AVATAR_EMPTY = 'PROFILE_AVATAR_EMPTY';
  public const PROFILE_BIRTH_DATE_EMPTY = 'PROFILE_BIRTH_DATE_EMPTY';

  public const PASSWORD_EMPTY = 'PASSWORD_EMPTY';

  // 429
  public const RATE_LIMITED = 'RATE_LIMITED';

  // 500
  public const INTERNAL_ERROR = 'INTERNAL_ERROR';
  public const DB_ERROR = 'DB_ERROR';
  public const SAVE_FAILED = 'SAVE_FAILED';
  public const DELETE_FAILED = 'DELETE_FAILED';

  public const COMMENT_CREATE_FAILED = 'COMMENT_CREATE_FAILED';
  public const COMMENT_UPDATE_FAILED = 'COMMENT_UPDATE_FAILED';
  public const COMMENT_DELETE_FAILED = 'COMMENT_DELETE_FAILED';

  public const NOTIFICATION_CREATE_FAILED = 'NOTIFICATION_CREATE_FAILED';
  public const NOTIFICATION_UPDATE_FAILED = 'NOTIFICATION_UPDATE_FAILED';

  public const POST_CREATE_FAILED = 'POST_CREATE_FAILED';
  public const POST_UPDATE_FAILED = 'POST_UPDATE_FAILED';
  public const POST_DELETE_FAILED = 'POST_DELETE_FAILED';

  public const PROFILE_CREATE_FAILED = 'PROFILE_CREATE_FAILED';
  public const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';

  public const REACTION_SAVE_FAILED = 'REACTION_SAVE_FAILED';

  public const USER_CREATE_FAILED = 'USER_CREATE_FAILED';
  public const PASSWORD_INVALID = 'PASSWORD_INVALID';
  public const PASSWORD_MISMATCH = 'PASSWORD_MISMATCH';
  public const PASSWORD_CHANGE_FAILED = 'PASSWORD_CHANGE_FAILED';
  public const USER_STATUS_CHANGE_FAILED = 'USER_STATUS_CHANGE_FAILED';

  public const SESSION_CREATE_FAILED = 'SESSION_CREATE_FAILED';
  public const SESSION_DELETE_FAILED = 'SESSION_DELETE_FAILED';
}
